/** @format */
import { AppRegistry, Platform } from 'react-native';
import { ScriptManager, Script } from '@callstack/repack/client';
import App from './App';

console.log('App starting in JS...');

// Variable to store the remote module registry
let remoteRegistry = null;

async function getRegistry() {
  const host = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';
  if (remoteRegistry) return remoteRegistry;

  try {
    const response = await fetch(`http://${host}:3000/assets`);
    remoteRegistry = await response.json();
    console.log('📡 Module registry loaded from CDN:', remoteRegistry);
    return remoteRegistry;
  } catch (error) {
    console.warn('⚠️ Failed to load registry from CDN, using local fallback:', error);
    return [];
  }
}

// ScriptManager configuration to fetch remotes dynamically
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  const host = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';
  const registry = await getRegistry();

  // Find the module by scriptId or by caller (if it's a chunk)
  const remoteName = registry.find(a => a.id === scriptId) ? scriptId : caller;
  const asset = registry.find(a => a.id === remoteName);

  if (asset) {
    const isContainer = scriptId === remoteName;
    const extension = isContainer ? '.container.js.bundle' : '.chunk.bundle';

    let baseUrl = '';

    if (asset.is_dev_mode) {
      // If the module is in dev mode in the CDN, we use the module's dev server URL (e.g., port 9000)
      baseUrl = asset.url; // URL from CDN pointing to the dev server
    } else {
      // If it's in production mode in the CDN
      // The CDN structure is: /cdn/:id/:version/:platform/
      baseUrl = asset.url; // Base URL already formatted by the CDN
    }

    // Adapt the base URL to include platform and bundle type as generated by Rspack
    // The cdn/index.js logic currently returns up to /index.bundle, we adapt as needed
    const url = `${baseUrl.replace('index.bundle', '')}${Platform.OS}/${scriptId}${extension}`;

    console.log(`Resolving ${scriptId} from CDN at: ${url}`);

    return {
      url,
      cache: !asset.is_dev_mode,
    };
  }

  console.warn(`[ScriptManager] No registry entry found for scriptId: ${scriptId}, caller: ${caller}`);
  return undefined;
});

AppRegistry.registerComponent('esad-template-host', () => App);
